/// @description Insert description here
textList = ds_list_create();
ds_list_add( textList, draw_text_sprite( 80, 64, c_white, "MEGA MAN|BREAKPOINT|ENGINE BUILD" ) );
ds_list_add( textList, draw_text_sprite( 88, 96, c_white, "NEW GAME" ) );
ds_list_add( textList, draw_text_sprite( 88, 104, c_white, "LOAD GAME [dummy]" ) );
ds_list_add( textList, draw_text_sprite( 88, 112, c_white, "SETTINGS [dummy]" ) );
ds_list_add( textList, draw_text_sprite( 88, 120, c_white, "EXIT GAME" ) );
cursorSprite = spr_small_triangle;
cursorGrid = ds_grid_create( 4, 4 );
cursorIndex = 0;
ds_grid_set( cursorGrid, 0, 0, 80 );
ds_grid_set( cursorGrid, 0, 1, 96 );
ds_grid_set( cursorGrid, 0, 2, roomchange );
ds_grid_set( cursorGrid, 0, 3, rm_engine_test_boot );
ds_grid_set( cursorGrid, 1, 0, 80 );
ds_grid_set( cursorGrid, 1, 1, 104 );
ds_grid_set( cursorGrid, 1, 2, dummy );
ds_grid_set( cursorGrid, 2, 0, 80 );
ds_grid_set( cursorGrid, 2, 1, 112 );
ds_grid_set( cursorGrid, 2, 2, dummy );
ds_grid_set( cursorGrid, 3, 0, 80 );
ds_grid_set( cursorGrid, 3, 1, 120 );
ds_grid_set( cursorGrid, 3, 2, quit );